<?php

/**
 * The Business Meta Box
 *
 * This class defines all fields for the custom term wpbe_team.
 *
 * Initially generated by the WordPress Meta Box Generator at http://goo.gl/8nwllb
 *
 * @since      0.2.0
 * @package    Wp_Business_Essentials
 * @subpackage Wp_Business_Essentials/includes
 * @author     Marvin Kronenfeld (WP-Styles.de) <hello@wp-styles.de>
 */
class Wp_Business_Essentials_Meta_Box_Business extends Wp_Business_Essentials_Meta_Box {
	protected $screens = array(
		'wpbe_business'
	);


	/**
	 * Hooks into WordPress' add_meta_boxes function.
	 *
	 * Goes through screens (post types) and adds the meta box.
	 *
	 * @since   0.2.0
	 */
	public function add_meta_boxes() {
		foreach ( $this->screens as $screen ) {
			add_meta_box(
				'wpbe-meta-box-team-member',
				__( 'Business', 'wp-business-essentials' ),
				array( $this, 'add_meta_box_callback' ),
				$screen,
				'advanced',
				'default'
			);
		}
	}

	/**
	 * Set fields.
	 *
	 * Outsoured from private property above to enable text domains.
	 *
	 * @todo opening hours
	 * @todo images?
	 *
	 *
	 * @since    0.2.0
	 */
	protected function set_fields() {
		$this->fields = array(
			array(
				'id'    => 'wpbe-business-phone',
				'label' => __( 'Phone', 'wp-business-essentials' ),
				'type'  => 'tel',
			),
			array(
				'id'    => 'wpbe-business-email',
				'label' => __( 'E-Mail', 'wp-business-essentials' ),
				'type'  => 'email',
			),
			array(
				'id'    => 'wpbe-business-url',
				'label' => __( 'Website', 'wp-business-essentials' ),
				'type'  => 'url',
			),
			array(
				'id'    => 'wpbe-business-country',
				'label' => __( 'Country', 'wp-business-essentials' ),
				'type'  => 'text',
			),
			array(
				'id'    => 'wpbe-business-address',
				'label' => __( 'Street Address', 'wp-business-essentials' ),
				'type'  => 'textarea',
			),
			array(
				'id'    => 'wpbe-business-zip',
				'label' => __( 'Postal code', 'wp-business-essentials' ),
				'type'  => 'text',
			),
			array(
				'id'    => 'wpbe-business-city',
				'label' => __( 'City', 'wp-business-essentials' ),
				'type'  => 'city',
			),
		);
	}

	/**
	 * Generates the HTML for the meta box
	 *
	 * @param object $post WordPress post object
	 *
	 * @since    0.2.0
	 */
	public function add_meta_box_callback( $post ) {
		wp_nonce_field( 'meta_box_data', 'meta_box_nonce' );
//		_e( 'Socializing is an important part of building good relationships. Let your visitors know how they can reach you best.', 'wp-business-essentials' );
		$this->generate_fields( $post );
		//echo '<hr>';
		//$this->generate_shortcodes( $post );
	}

}
